name: sigma-reparam-py310
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2023.01.10=hecd8cb5_0
  - libffi=3.4.2=hecd8cb5_6
  - ncurses=6.4=hcec6c5f_0
  - openssl=1.1.1t=hca72f7f_0
  - python=3.10.11=h218abb5_2
  - pip=23.0.1
  - readline=8.2=hca72f7f_0
  - sqlite=3.41.2=h6c40b1e_0
  - tk=8.6.12=h5d9f67b_0
  - tzdata=2023c=h04d1e81_0
  - xz=5.2.10=h6c40b1e_1
  - zlib=1.2.13=h4dc903c_0
  - pip:
    - git+https://github.com/rwightman/pytorch-image-models@9ee846ff0cbbc05a99b45140aa6d84083bcf6488
    - torch>=2.0.0
    - torchvision>=0.15.1
